name: RADICAL-AsyncFlow
icon: https://radical-cybertools.github.io/assets/radical-logo-transparent.png
headline: High Performance Asynchronous Workflow Scripting Library
description: |
  RADICAL-AsyncFlow (RAF) is an asynchronous scripting library for building 
  high-performance, scalable workflows that run on HPC systems, clusters, 
  and local machines. Designed for flexibility and speed, it allows users 
  to compose complex workflows from async and sync tasks with clear 
  dependencies, while ensuring efficient execution at any scale with 
  different execution backends.

language: Python

release:
  version: 0.2.0
  date: 2025-09-02
  url: https://pypi.org/project/radical.asyncflow/

documentation:
  general: https://radical-cybertools.github.io/radical.asyncflow/
  installation: https://radical-cybertools.github.io/radical.asyncflow/install/
  tutorial: https://radical-cybertools.github.io/radical.asyncflow/basic/index.html

