site_name: AsyncFlow
site_url: 'https://github.com/radical-cybertools/async.flow'
repo_name: 'AsyncFlow'
repo_url: 'https://github.com/radical-cybertools/async.flow'
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: black
        accent: indigo
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: black
        accent: indigo

  highlightjs: true
  hljs_languages:
        - yaml
        - json
        - bash
  features:
      - header.autohide
      - navigation.instant
      - navigation.top
      - navigation.tabs
      - navigation.tabs.sticky
      - search.highlight
      - search.share
      - search.suggest
      - content.code.annotate
      - content.tooltips
      - content.tabs.link
      - content.code.copy
  font:
    text: 'Segoe UI'
    code: Roboto Mono

# Plugins
plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
  - gen-files:
      scripts:
        - docs/generate_api_references.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true


# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference:
      - AsyncFlow: api/


extra_css:
  - css/extra.css

