site_name: SyncFlow Docs
theme:
    name: material
docs_dir: docs/src-mkdocs

plugins:
    - search
    - gen-files:
        scripts:
            - docs/scripts/gen_reference_nav.py
    - literate-nav:
        nav_file: reference/SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                inventories:
                    - https://docs.python.org/3/objects.inv
                options:
                    show_source: true
                    merge_init_into_class: true
                    docstring_style: google
                    show_if_no_docstring: true
                    heading_level: 2
                    show_root_heading: true
                    show_root_full_path: true
                    show_object_full_path: false
                    show_category_heading: true
                    members: true
                    inherited_members: true
    - mkdocs-jupyter:
        include_source: True
        execute: False
    - section-index

nav:
    - Home: index.md
    - Tutorials:
        - Introduction: tutorials/run_sync_async.ipynb
    - API Reference: reference/