[tox]
min_version = 4.0
envlist = pre-commit,py39,py310,py311,py312,py313
isolated_build = true

# Pre-commit must pass before any other env runs
[testenv:pre-commit]
extras = dev
allowlist_externals = pre-commit
commands = pre-commit run --all-files

# Unit test env
[testenv]
depends = pre-commit
extras = dev
commands = pytest tests/unit {posargs}

# Integration test
[testenv:{py39,py310,py311,py312,py313}-all]
depends = pre-commit
extras = dev
commands = pytest tests/integration {posargs}

# Linting
[testenv:lint]
depends = pre-commit
extras = lint
commands =
    ruff check src tests
    ruff format --check src tests

# Formatting
[testenv:format]
extras = lint
commands =
    ruff format src tests
    ruff check --fix src tests

# Coverage
[testenv:coverage]
depends = pre-commit
extras = dev
commands = pytest --cov=radical.asyncflow --cov-report=html --cov-report=term {posargs}

# Docs
[testenv:docs]
depends = pre-commit
extras = doc
allowlist_externals = mkdocs
commands = mkdocs build --strict
